### ISSUE TITLE
Wrong level up message

### ISSUE THREAD

**Issue by Skywebz** [tobiyas/RacesAndClasses#10]
Apparently, the levelup message actually displays "You are now %level%+1"

Example : my player datas and action bars say I'm level 5, though my level up message said I'm level 6.

Not a really important issue, but I felt like I had to signal it.

**Comment by tobiyas** [comment]
Thank you very much, you are 100% correct. Fixed with this [Commit](https://github.com/tobiyas/RacesAndClasses/commit/a112567817a55a33a092a9e0d4d9abe1a07a5b66).
