### ISSUE TITLE
Got Event! Spam in console.

### ISSUE THREAD

**Issue by ninmore** [tobiyas/RacesAndClasses#5]
Hey I had a problem with a server I was working on and for some reason a plugin was printing to the console "Got Event!" it took me sometime to find what plugin it was and the event. 

To save you time I found the exact method that it spamming the console. Here is the class and the line where the print to console is used [LINK](https://github.com/tobiyas/RacesAndClasses/blob/master/src/main/java/de/tobiyas/racesandclasses/traitcontainer/traits/defaultraits/passive/PassiveAggroTrait/PassiveAggroTrait.java#L113).

Cheers o/

**Comment by tobiyas** [comment]
Sorry. You are absolutely correct.
Was for debug purpose. Seem to forgot to remove it.
Thank you very much!
